### ISSUE TITLE
Recommended alternative that actually has same type of features

### ISSUE THREAD

**Issue by dlong500** [ggarek/react-selectize#7]
I'm sorry to see you aren't maintaining the project anymore, but do you know of a React-based alternative that actually does what Selectize does?  The material-ui framework you mention in the README doesn't even have a type-ahead component at all yet, much less one that has the advanced features of Selectize or Chosen.

Also, can you give some insight into why you stopped maintaining it?  Is it just because you don't have the time or because you had problems with the implementation?  Thanks.

**Comment by aleemb** [comment]
@dlong500 https://github.com/JedWatson/react-select/

**Comment by dlong500** [comment]
Thanks.  I've been testing out a variety of options including that one and haven't quite found one that implements everything I need.  Maybe I'll have the time to write my own React component from scratch at some point (or at least contribute to an existing component).
